### PR TITLE
Use inline R code instead of a code chunk

### PR DESCRIPTION
**Pull request by yihui**
to print out the user name and date/time

### CODE REVIEW

**Comment by ismayc** [comment]
Sounds good.  Thanks for the feedback!  Can you tell me why this is preferred?

**Comment by yihui** [comment]
Sure. Just compare

image

with

> Book was last updated by Chester on Tuesday, January 10, 2017 21:08:44 EST.

I think none of the two hashes `##`, `[1]`, double quotes, and the background color is essential, and all can be visually distractive to readers. I think blending the information into a normal paragraph should be enough.

**Comment by ismayc** [comment]
Ah, so for stylistic reasons.  I agree that does look nicer.  I thought there might have been something else I was missing.

**Comment by yihui** [comment]
No, nothing technical. I just don't want readers to ask questions like, what does `##` mean? What is `[1]`? ... Those who are familiar with knitr will get it quickly, but those who are not can be confused.

**Comment by ismayc** [comment]
Much appreciated!  Especially in the very beginning of the book.

**Comment by ismayc** [comment]
It took us awhile to figure out exactly how to publish the book, whether we should branch, and have a GitHub repo attached to it.  Unfortunately, in that process, I forgot to update the Edit link in the book to point to the correct repo:  https://github.com/ismayc/moderndiver-book.  In hindsight, I think adding the book into an R package as you have done for `bookdown` makes the most sense and we'll be shifting that way in the coming months.

**Pull request merged**
